// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    BarChart: typeof import('./components/BarChart.vue')['default']
    FileExplorer: typeof import('./components/FileExplorer.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    User: typeof import('./components/User.vue')['default']
  }
}
